use_frameworks!

target 'DotLoadingIndicator_Example' do
  pod 'DotLoadingIndicator', :path => '../'

  target 'DotLoadingIndicator_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
